# Generated by Django 4.0.2 on 2022-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picme', '0002_remove_image_category_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='image_list', to='picme.Category'),
        ),
    ]
