# Generated by Django 4.0.2 on 2022-02-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picme', '0003_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
